apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  labels:
    app: echoserver
    partition: poc
spec:
  selector:
    app: echoserver
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080